exp_name: 'efficientnetv2_rw_s_arcface'
outdir: './experiments/'

num_gpu: 1
gpu_id: 0

dataset:
    root: './datasets/CompCars/data/image/'
    # train_list: './datasets/CompCars/annotation/train.txt'
    train_list: './datasets/CompCars/annotation/train_full.txt'
    val_list: './datasets/CompCars/annotation/val.txt'
    seed: 42
    num_of_classes: 1716
    input_size: 224
    batch_size: 128
    augmentations: 'complex'
    augmentations_valid: 'default'
    num_workers: 16


model:
    model_name: 'efficientnetv2_rw_s'
    pretrained: True
    use_fc: True
    fc_dim: 512
    dropout: 0.5
    loss_module: "arcface"
    s: 30.0
    margin: 0.3
    theta_zero: 0.785

train:
    full_training: True # Train on fuill data without validation
    debug: False
    warmup: False
    optimizer: 'SGD'
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    lr_scheduler:
        name: 'MultiStepLR'
        step_size: 30
        milestones: [10, 30, 60, 90]
        eta_min: 0.0001
        T_max: 4
        gamma: 0.1
    n_epoch: 200
    label_smoothing: false
    eps: 0.01
    freq_vis: 200
