exp_name: 'metric_learning_resnet18'
outdir: './experiments/'

num_gpu: 1

dataset:
    root: './datasets/CompCars/data/image/'
    train_list: './datasets/CompCars/annotation/train.txt'
    val_list: './datasets/CompCars/annotation/val.txt'
    seed: 42
    num_of_classes: 1716
    input_size: 224
    batch_size: 256
    augmentations: 'default'
    augmentations_valid: 'default'
    num_workers: 16


model:
    arch: 'resnet18'
    embedding_size: 512

train:
    optimizer: 'SGD'
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.
    lr_schedule:
        name: 'StepLR'
        step_size: 30
        gamma: 0.1
    n_epoch: 125
    label_smoothing: false
    eps: 0.01
    freq_vis: 10
