root: './datasets/public_test/images/'
test_list: './datasets/public_test/images_w_boxes.csv'
pairs_list: './datasets/public_test/submission_list.csv'
batch_size: 128
augmentations: 'default'
augmentations_valid: 'default'
num_workers: 16

